// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class AntiCheatEvent
{
    public Guid AntiCheatEventId { get; set; }

    public Guid AttemptId { get; set; }

    public string EventType { get; set; }

    public DateTime EventAt { get; set; }

    public string MetaJson { get; set; }

    public virtual AssessmentAttempt Attempt { get; set; }
}