// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class ApplicationAiScore
{
    public Guid AiScoreId { get; set; }

    public Guid ApplicationId { get; set; }

    public decimal MatchingScore { get; set; }

    public string MatchedSkillsJson { get; set; }

    public string Model { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Application Application { get; set; }
}