// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class ApplicationStageHistory
{
    public Guid HistoryId { get; set; }

    public Guid ApplicationId { get; set; }

    public Guid? FromStageId { get; set; }

    public Guid ToStageId { get; set; }

    public Guid? ChangedBy { get; set; }

    public string Reason { get; set; }

    public DateTime ChangedAt { get; set; }

    public virtual Application Application { get; set; }

    public virtual User ChangedByNavigation { get; set; }

    public virtual PipelineStage FromStage { get; set; }

    public virtual PipelineStage ToStage { get; set; }
}