// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class ApplicationNote
{
    public Guid NoteId { get; set; }

    public Guid ApplicationId { get; set; }

    public string Note { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Application Application { get; set; }

    public virtual User CreatedByNavigation { get; set; }
}