// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class AssessmentInvite
{
    public Guid InviteId { get; set; }

    public Guid ApplicationId { get; set; }

    public Guid AssessmentId { get; set; }

    public string Code { get; set; }

    public DateTime ExpiresAt { get; set; }

    public string SentToEmail { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UsedAt { get; set; }

    public virtual Application Application { get; set; }

    public virtual Assessment Assessment { get; set; }

    public virtual ICollection<AssessmentAttempt> AssessmentAttempts { get; set; } = new List<AssessmentAttempt>();
}