// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class AssessmentAnswer
{
    public Guid AnswerId { get; set; }

    public Guid AttemptId { get; set; }

    public Guid BankQuestionId { get; set; }

    public string SelectedOptionIdsJson { get; set; }

    public bool? IsCorrect { get; set; }

    public decimal? PointsEarned { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual AssessmentAttempt Attempt { get; set; }

    public virtual QuestionBank BankQuestion { get; set; }
}