// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class Assessment
{
    public Guid AssessmentId { get; set; }

    public string Name { get; set; }

    public string Mode { get; set; }

    public int DurationMinutes { get; set; }

    public decimal PassScore { get; set; }

    public bool ShowResultToCandidate { get; set; }

    public int? RandomQuestionCount { get; set; }

    public string RandomTags { get; set; }

    public bool IsActive { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<AssessmentInvite> AssessmentInvites { get; set; } = new List<AssessmentInvite>();

    public virtual ICollection<AssessmentQuestion> AssessmentQuestions { get; set; } = new List<AssessmentQuestion>();

    public virtual User CreatedByNavigation { get; set; }
}