// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class AssessmentQuestion
{
    public Guid AssessmentId { get; set; }

    public Guid BankQuestionId { get; set; }

    public int SortOrder { get; set; }

    public decimal Points { get; set; }

    public virtual Assessment Assessment { get; set; }

    public virtual QuestionBank BankQuestion { get; set; }
}