// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class AssessmentAttempt
{
    public Guid AttemptId { get; set; }

    public Guid InviteId { get; set; }

    public DateTime StartedAt { get; set; }

    public DateTime? SubmittedAt { get; set; }

    public decimal? Score { get; set; }

    public bool? Passed { get; set; }

    public string Status { get; set; }

    public string CandidateIp { get; set; }

    public string UserAgent { get; set; }

    public virtual ICollection<AntiCheatEvent> AntiCheatEvents { get; set; } = new List<AntiCheatEvent>();

    public virtual ICollection<AssessmentAnswer> AssessmentAnswers { get; set; } = new List<AssessmentAnswer>();

    public virtual AssessmentInvite Invite { get; set; }
}