// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class AutomationRule
{
    public Guid RuleId { get; set; }

    public string Name { get; set; }

    public string TriggerEvent { get; set; }

    public Guid TemplateId { get; set; }

    public int DelayMinutes { get; set; }

    public bool IsActive { get; set; }

    public string ConditionJson { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual EmailTemplate Template { get; set; }
}