// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class CandidateSkill
{
    public Guid CandidateId { get; set; }

    public Guid SkillId { get; set; }

    public byte? Level { get; set; }

    public decimal? Years { get; set; }

    public virtual Candidate Candidate { get; set; }

    public virtual Skill Skill { get; set; }
}