// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class CandidateEducation
{
    public Guid EducationId { get; set; }

    public Guid CandidateId { get; set; }

    public string School { get; set; }

    public string Degree { get; set; }

    public string Field { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public virtual Candidate Candidate { get; set; }
}