// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class CandidateExperience
{
    public Guid ExperienceId { get; set; }

    public Guid CandidateId { get; set; }

    public string Company { get; set; }

    public string Title { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public string Description { get; set; }

    public virtual Candidate Candidate { get; set; }
}