// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class ChatMessage
{
    public Guid ChatMessageId { get; set; }

    public Guid ChatSessionId { get; set; }

    public string Sender { get; set; }

    public string Message { get; set; }

    public DateTime CreatedAt { get; set; }

    public string MetaJson { get; set; }

    public virtual ChatSession ChatSession { get; set; }
}