// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class ChatSession
{
    public Guid ChatSessionId { get; set; }

    public Guid ApplicationId { get; set; }

    public DateTime StartedAt { get; set; }

    public DateTime? EndedAt { get; set; }

    public string Channel { get; set; }

    public virtual Application Application { get; set; }

    public virtual ICollection<ChatMessage> ChatMessages { get; set; } = new List<ChatMessage>();
}