// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class EmailSendLog
{
    public Guid EmailSendLogId { get; set; }

    public Guid EmailQueueId { get; set; }

    public string Provider { get; set; }

    public string ProviderMessageId { get; set; }

    public string Result { get; set; }

    public string Detail { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual EmailQueue EmailQueue { get; set; }
}