// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class EmailTemplate
{
    public Guid TemplateId { get; set; }

    public string Code { get; set; }

    public string Subject { get; set; }

    public string BodyHtml { get; set; }

    public string BodyText { get; set; }

    public bool IsActive { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<AutomationRule> AutomationRules { get; set; } = new List<AutomationRule>();

    public virtual User CreatedByNavigation { get; set; }
}