// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class EmailQueue
{
    public Guid EmailQueueId { get; set; }

    public string ToEmail { get; set; }

    public string ToName { get; set; }

    public string Subject { get; set; }

    public string BodyHtml { get; set; }

    public string BodyText { get; set; }

    public string Status { get; set; }

    public string RelatedType { get; set; }

    public Guid? RelatedId { get; set; }

    public DateTime ScheduledAt { get; set; }

    public DateTime? SentAt { get; set; }

    public string FailReason { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<EmailSendLog> EmailSendLogs { get; set; } = new List<EmailSendLog>();
}