// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class File
{
    public Guid FileId { get; set; }

    public string Provider { get; set; }

    public string OriginalFileName { get; set; }

    public string StoredFileName { get; set; }

    public string MimeType { get; set; }

    public long? SizeBytes { get; set; }

    public string Sha256 { get; set; }

    public string Url { get; set; }

    public string LocalPath { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<CandidateDocument> CandidateDocuments { get; set; } = new List<CandidateDocument>();
}