// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class InterviewScorecard
{
    public Guid ScorecardId { get; set; }

    public Guid InterviewId { get; set; }

    public string CriteriaCode { get; set; }

    public string CriteriaName { get; set; }

    public int MaxScore { get; set; }

    public int SortOrder { get; set; }

    public virtual Interview Interview { get; set; }
}