// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace UTC_DATN.Entities;

public partial class Interview
{
    public Guid InterviewId { get; set; }

    public Guid ApplicationId { get; set; }

    public string Title { get; set; }

    public DateTime ScheduledStart { get; set; }

    public DateTime ScheduledEnd { get; set; }

    public string MeetingLink { get; set; }

    public string Location { get; set; }

    public string Status { get; set; } = null!; // Modified

    public Guid? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public Guid? InterviewerId { get; set; } // Reordered

    public virtual Application Application { get; set; } = null!; // Modified

    public virtual User? CreatedByNavigation { get; set; } // Modified

    public virtual ICollection<InterviewFeedback> InterviewFeedbacks { get; set; } = new List<InterviewFeedback>();

    public virtual ICollection<InterviewScorecard> InterviewScorecards { get; set; } = new List<InterviewScorecard>();

    public virtual ICollection<Interviewer> Interviewer { get; set; } = new List<Interviewer>(); // Renamed from Interviewers

    [ForeignKey("InterviewerId")] // Added ForeignKey attribute
    public virtual User? InterviewerUser { get; set; } // Added
}