// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class InterviewFeedback
{
    public Guid FeedbackId { get; set; }

    public Guid InterviewId { get; set; }

    public Guid UserId { get; set; }

    public decimal? OverallScore { get; set; }

    public string Recommendation { get; set; }

    public string Notes { get; set; }

    public string DetailScoresJson { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Interview Interview { get; set; }

    public virtual User User { get; set; }
}