// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class Interview
{
    public Guid InterviewId { get; set; }

    public Guid ApplicationId { get; set; }

    public string Title { get; set; }

    public DateTime ScheduledStart { get; set; }

    public DateTime ScheduledEnd { get; set; }

    public string MeetingLink { get; set; }

    public string Location { get; set; }

    public string Status { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Application Application { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<InterviewFeedback> InterviewFeedbacks { get; set; } = new List<InterviewFeedback>();

    public virtual ICollection<InterviewScorecard> InterviewScorecards { get; set; } = new List<InterviewScorecard>();

    public virtual ICollection<Interviewer> Interviewers { get; set; } = new List<Interviewer>();
}