// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class Interviewer
{
    public Guid InterviewId { get; set; }

    public Guid UserId { get; set; }

    public string RoleInPanel { get; set; }

    public virtual Interview Interview { get; set; }

    public virtual User User { get; set; }
}