// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class JobSkillMap
{
    public Guid JobId { get; set; }

    public Guid SkillId { get; set; }

    public byte Weight { get; set; }

    public virtual Job Job { get; set; }

    public virtual Skill Skill { get; set; }
}