// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class PreScreenAnswer
{
    public Guid AnswerId { get; set; }

    public Guid ApplicationId { get; set; }

    public Guid QuestionId { get; set; }

    public string Answer { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Application Application { get; set; }

    public virtual PreScreenQuestion Question { get; set; }
}