// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class PreScreenQuestion
{
    public Guid QuestionId { get; set; }

    public string Code { get; set; }

    public string Question { get; set; }

    public string AnswerType { get; set; }

    public string OptionsJson { get; set; }

    public bool IsActive { get; set; }

    public int SortOrder { get; set; }

    public virtual ICollection<PreScreenAnswer> PreScreenAnswers { get; set; } = new List<PreScreenAnswer>();
}