// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class QuestionOption
{
    public Guid OptionId { get; set; }

    public Guid BankQuestionId { get; set; }

    public string Content { get; set; }

    public bool IsCorrect { get; set; }

    public int SortOrder { get; set; }

    public virtual QuestionBank BankQuestion { get; set; }
}